# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('z_or_isp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findJob.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('time', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('executor', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findJob.Men')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findJob.Perk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findJob.Men')),
            ],
        ),
        migrations.AddField(
            model_name='pdcategory',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findJob.Perk'),
        ),
    ]
